// ============================================================
// ALL FAKE DEMO DATA FOR AI WHATSAPP CRM
// ============================================================

// ---- CONTACTS / CHATS ----
export const contacts = [
  {
    id: '1',
    name: 'Aarav Shah',
    phone: '+91 98765 43210',
    avatar: 'AS',
    color: '#2563EB',
    lastMessage: 'Can you send me the pricing details?',
    time: '2m ago',
    unread: 3,
    online: true,
    pinned: true,
    tags: ['Hot Lead', 'Enterprise'],
    source: 'Website Form',
    budget: '₹2,50,000',
    aiScore: 92,
    stage: 'Interested',
  },
  {
    id: '2',
    name: 'Priya Menon',
    phone: '+91 87654 32109',
    avatar: 'PM',
    color: '#7C3AED',
    lastMessage: 'I will get back to you tomorrow 👍',
    time: '15m ago',
    unread: 1,
    online: true,
    pinned: true,
    tags: ['Warm', 'Startup'],
    source: 'Instagram Ad',
    budget: '₹75,000',
    aiScore: 74,
    stage: 'Contacted',
  },
  {
    id: '3',
    name: 'Ravi Kumar',
    phone: '+91 76543 21098',
    avatar: 'RK',
    color: '#06B6D4',
    lastMessage: 'When can we schedule a demo call?',
    time: '1h ago',
    unread: 0,
    online: false,
    pinned: false,
    tags: ['SMB'],
    source: 'Referral',
    budget: '₹1,20,000',
    aiScore: 81,
    stage: 'Proposal Sent',
  },
  {
    id: '4',
    name: 'Sneha Patel',
    phone: '+91 65432 10987',
    avatar: 'SP',
    color: '#10B981',
    lastMessage: 'Okay sounds great! Let me check with my team.',
    time: '3h ago',
    unread: 0,
    online: false,
    pinned: false,
    tags: ['Agency', 'High Value'],
    source: 'LinkedIn',
    budget: '₹4,50,000',
    aiScore: 88,
    stage: 'Proposal Sent',
  },
  {
    id: '5',
    name: 'Arjun Nair',
    phone: '+91 54321 09876',
    avatar: 'AN',
    color: '#F59E0B',
    lastMessage: 'Do you have a free trial available?',
    time: '5h ago',
    unread: 2,
    online: true,
    pinned: false,
    tags: ['New Lead'],
    source: 'Google Ads',
    budget: '₹45,000',
    aiScore: 62,
    stage: 'New Lead',
  },
  {
    id: '6',
    name: 'Kavya Reddy',
    phone: '+91 43210 98765',
    avatar: 'KR',
    color: '#EF4444',
    lastMessage: 'The payment is pending, need invoice.',
    time: '1d ago',
    unread: 0,
    online: false,
    pinned: false,
    tags: ['Payment Pending', 'Agency'],
    source: 'Website Form',
    budget: '₹1,80,000',
    aiScore: 95,
    stage: 'Payment Pending',
  },
  {
    id: '7',
    name: 'Dev Sharma',
    phone: '+91 32109 87654',
    avatar: 'DS',
    color: '#8B5CF6',
    lastMessage: 'Thanks for the quick support! 🙏',
    time: '2d ago',
    unread: 0,
    online: false,
    pinned: false,
    tags: ['Closed Won', 'Enterprise'],
    source: 'Referral',
    budget: '₹6,00,000',
    aiScore: 99,
    stage: 'Closed',
  },
  {
    id: '8',
    name: 'Meera Joshi',
    phone: '+91 21098 76543',
    avatar: 'MJ',
    color: '#EC4899',
    lastMessage: 'I need to think about it. Will message you.',
    time: '3d ago',
    unread: 0,
    online: false,
    pinned: false,
    tags: ['Cold'],
    source: 'Facebook Ad',
    budget: '₹35,000',
    aiScore: 28,
    stage: 'Contacted',
  },
];

// ---- CHAT MESSAGES ----
export const chatMessages: Record<string, ChatMessage[]> = {
  '1': [
    { id: '1', sender: 'them', text: 'Hi! I saw your ad on Google. Can you tell me more about your WhatsApp CRM?', time: '10:23 AM', type: 'text' },
    { id: '2', sender: 'me', text: 'Hello Aarav! Welcome 👋 We offer a full AI-powered WhatsApp CRM for businesses. Would you like a quick demo?', time: '10:25 AM', type: 'text' },
    { id: '3', sender: 'them', text: 'Yes definitely! What are the pricing plans?', time: '10:26 AM', type: 'text' },
    { id: '4', sender: 'me', text: 'Great! We have 3 plans starting at ₹2,999/month. The Pro plan at ₹6,999/month is most popular for agencies.', time: '10:28 AM', type: 'text' },
    { id: '5', sender: 'them', text: 'Interesting. Can you send me the complete pricing details with all features?', time: '10:45 AM', type: 'text' },
    { id: '6', sender: 'ai_suggestion', text: 'AI Suggestion: Reply with the pricing PDF and offer a 14-day free trial to increase conversion.', time: '', type: 'ai' },
    { id: '7', sender: 'them', text: 'Can you send me the pricing details?', time: '12:01 PM', type: 'text' },
  ],
  '2': [
    { id: '1', sender: 'me', text: 'Hi Priya! Following up on our demo call yesterday. Any questions?', time: '9:00 AM', type: 'text' },
    { id: '2', sender: 'them', text: 'Yes! The platform looked great. I need to discuss budget with my co-founder.', time: '9:15 AM', type: 'text' },
    { id: '3', sender: 'me', text: 'Absolutely, take your time! Let me know if you need any clarifications 😊', time: '9:17 AM', type: 'text' },
    { id: '4', sender: 'them', text: 'I will get back to you tomorrow 👍', time: '9:20 AM', type: 'text' },
  ],
};

export interface ChatMessage {
  id: string;
  sender: 'me' | 'them' | 'ai_suggestion';
  text: string;
  time: string;
  type: 'text' | 'ai' | 'image';
}

// ---- ANALYTICS DATA ----
export const revenueData = [
  { month: 'Jan', revenue: 48000, target: 45000, leads: 82 },
  { month: 'Feb', revenue: 62000, target: 55000, leads: 98 },
  { month: 'Mar', revenue: 55000, target: 60000, leads: 87 },
  { month: 'Apr', revenue: 78000, target: 70000, leads: 125 },
  { month: 'May', revenue: 91000, target: 85000, leads: 148 },
  { month: 'Jun', revenue: 85000, target: 90000, leads: 137 },
  { month: 'Jul', revenue: 112000, target: 100000, leads: 176 },
  { month: 'Aug', revenue: 128000, target: 115000, leads: 198 },
  { month: 'Sep', revenue: 142000, target: 130000, leads: 215 },
  { month: 'Oct', revenue: 138000, target: 140000, leads: 210 },
  { month: 'Nov', revenue: 165000, target: 155000, leads: 242 },
  { month: 'Dec', revenue: 198000, target: 180000, leads: 289 },
];

export const responseTimeData = [
  { day: 'Mon', time: 4.2 },
  { day: 'Tue', time: 3.8 },
  { day: 'Wed', time: 5.1 },
  { day: 'Thu', time: 2.9 },
  { day: 'Fri', time: 3.5 },
  { day: 'Sat', time: 6.2 },
  { day: 'Sun', time: 7.8 },
];

export const conversionData = [
  { name: 'Converted', value: 68, color: '#2563EB' },
  { name: 'In Progress', value: 22, color: '#7C3AED' },
  { name: 'Lost', value: 10, color: '#E2E8F0' },
];

export const channelData = [
  { name: 'WhatsApp', value: 52, color: '#25D366' },
  { name: 'Website', value: 24, color: '#2563EB' },
  { name: 'Instagram', value: 15, color: '#E1306C' },
  { name: 'LinkedIn', value: 9, color: '#0077B5' },
];

// ---- STATS ----
export const dashboardStats = [
  {
    id: '1',
    title: 'Monthly Revenue',
    value: '₹19.8L',
    change: '+24.5%',
    positive: true,
    subtitle: 'vs last month',
    color: '#2563EB',
    icon: 'TrendingUp',
  },
  {
    id: '2',
    title: 'Active Chats',
    value: '247',
    change: '+18',
    positive: true,
    subtitle: 'today',
    color: '#7C3AED',
    icon: 'MessageCircle',
  },
  {
    id: '3',
    title: 'Conversion Rate',
    value: '68.4%',
    change: '+5.2%',
    positive: true,
    subtitle: 'this month',
    color: '#06B6D4',
    icon: 'Target',
  },
  {
    id: '4',
    title: 'Avg Response Time',
    value: '2.3 min',
    change: '-0.8 min',
    positive: true,
    subtitle: 'with AI assist',
    color: '#10B981',
    icon: 'Zap',
  },
];

// ---- LEADS (KANBAN) ----
export interface Lead {
  id: string;
  name: string;
  company: string;
  avatar: string;
  color: string;
  budget: string;
  aiScore: number;
  priority: 'Hot' | 'Warm' | 'Cold';
  tags: string[];
  deadline: string;
  source: string;
  aiSuggestion: string;
  stage: KanbanStage;
  phone: string;
}

export type KanbanStage = 'New Lead' | 'Contacted' | 'Interested' | 'Proposal Sent' | 'Payment Pending' | 'Closed';

export const kanbanStages: KanbanStage[] = [
  'New Lead',
  'Contacted',
  'Interested',
  'Proposal Sent',
  'Payment Pending',
  'Closed',
];

export const stageColors: Record<KanbanStage, { bg: string; text: string; border: string }> = {
  'New Lead': { bg: '#F0F9FF', text: '#0369A1', border: '#BAE6FD' },
  'Contacted': { bg: '#FFF7ED', text: '#C2410C', border: '#FED7AA' },
  'Interested': { bg: '#F0FDF4', text: '#15803D', border: '#BBF7D0' },
  'Proposal Sent': { bg: '#EFF6FF', text: '#1D4ED8', border: '#BFDBFE' },
  'Payment Pending': { bg: '#FFF1F2', text: '#BE123C', border: '#FECDD3' },
  'Closed': { bg: '#F5F3FF', text: '#6D28D9', border: '#DDD6FE' },
};

export const leads: Lead[] = [
  {
    id: 'L001',
    name: 'Arjun Nair',
    company: 'TechNova Pvt Ltd',
    avatar: 'AN',
    color: '#F59E0B',
    budget: '₹45,000',
    aiScore: 62,
    priority: 'Warm',
    tags: ['Startup', 'SaaS'],
    deadline: 'Jun 15',
    source: 'Google Ads',
    aiSuggestion: 'Send free trial offer — high intent keywords detected',
    stage: 'New Lead',
    phone: '+91 54321 09876',
  },
  {
    id: 'L002',
    name: 'Pooja Singh',
    company: 'Digital Bloom Agency',
    avatar: 'PS',
    color: '#EC4899',
    budget: '₹2,00,000',
    aiScore: 78,
    priority: 'Hot',
    tags: ['Agency', 'High Value'],
    deadline: 'Jun 10',
    source: 'Referral',
    aiSuggestion: 'High budget client — escalate to senior sales rep',
    stage: 'New Lead',
    phone: '+91 99887 76655',
  },
  {
    id: 'L003',
    name: 'Meera Joshi',
    company: 'Style Hub',
    avatar: 'MJ',
    color: '#EC4899',
    budget: '₹35,000',
    aiScore: 28,
    priority: 'Cold',
    tags: ['E-commerce'],
    deadline: 'Jul 1',
    source: 'Facebook Ad',
    aiSuggestion: 'Low engagement — try automated nurture sequence',
    stage: 'Contacted',
    phone: '+91 21098 76543',
  },
  {
    id: 'L004',
    name: 'Priya Menon',
    company: 'CodeBridge Tech',
    avatar: 'PM',
    color: '#7C3AED',
    budget: '₹75,000',
    aiScore: 74,
    priority: 'Warm',
    tags: ['Startup'],
    deadline: 'Jun 20',
    source: 'Instagram Ad',
    aiSuggestion: 'Co-founder involved — schedule team demo call',
    stage: 'Contacted',
    phone: '+91 87654 32109',
  },
  {
    id: 'L005',
    name: 'Aarav Shah',
    company: 'GrowFast Solutions',
    avatar: 'AS',
    color: '#2563EB',
    budget: '₹2,50,000',
    aiScore: 92,
    priority: 'Hot',
    tags: ['Enterprise', 'WhatsApp API'],
    deadline: 'Jun 8',
    source: 'Website Form',
    aiSuggestion: 'Send pricing deck + ROI calculator to accelerate close',
    stage: 'Interested',
    phone: '+91 98765 43210',
  },
  {
    id: 'L006',
    name: 'Rahul Gupta',
    company: 'MarketPro India',
    avatar: 'RG',
    color: '#10B981',
    budget: '₹90,000',
    aiScore: 83,
    priority: 'Hot',
    tags: ['Marketing', 'Agency'],
    deadline: 'Jun 12',
    source: 'LinkedIn',
    aiSuggestion: 'Ready to buy — push for contract signing this week',
    stage: 'Interested',
    phone: '+91 78965 43210',
  },
  {
    id: 'L007',
    name: 'Ravi Kumar',
    company: 'CloudSync Labs',
    avatar: 'RK',
    color: '#06B6D4',
    budget: '₹1,20,000',
    aiScore: 81,
    priority: 'Hot',
    tags: ['SaaS', 'B2B'],
    deadline: 'Jun 5',
    source: 'Referral',
    aiSuggestion: 'Follow up on proposal — 2 days since sent',
    stage: 'Proposal Sent',
    phone: '+91 76543 21098',
  },
  {
    id: 'L008',
    name: 'Sneha Patel',
    company: 'BrandWave Agency',
    avatar: 'SP',
    color: '#10B981',
    budget: '₹4,50,000',
    aiScore: 88,
    priority: 'Hot',
    tags: ['Agency', 'Enterprise'],
    deadline: 'Jun 7',
    source: 'LinkedIn',
    aiSuggestion: 'Team review in progress — send case studies',
    stage: 'Proposal Sent',
    phone: '+91 65432 10987',
  },
  {
    id: 'L009',
    name: 'Kavya Reddy',
    company: 'Pixel Perfect Studio',
    avatar: 'KR',
    color: '#EF4444',
    budget: '₹1,80,000',
    aiScore: 95,
    priority: 'Hot',
    tags: ['Design', 'Agency'],
    deadline: 'Jun 3',
    source: 'Website Form',
    aiSuggestion: 'Invoice sent 3 days ago — send payment reminder now',
    stage: 'Payment Pending',
    phone: '+91 43210 98765',
  },
  {
    id: 'L010',
    name: 'Ankit Tiwari',
    company: 'RetailEdge Pvt Ltd',
    avatar: 'AT',
    color: '#F97316',
    budget: '₹3,20,000',
    aiScore: 91,
    priority: 'Hot',
    tags: ['Retail', 'Enterprise'],
    deadline: 'Jun 4',
    source: 'Cold Outreach',
    aiSuggestion: 'Payment overdue by 2 days — escalate immediately',
    stage: 'Payment Pending',
    phone: '+91 90012 34567',
  },
  {
    id: 'L011',
    name: 'Dev Sharma',
    company: 'InnovateTech Corp',
    avatar: 'DS',
    color: '#8B5CF6',
    budget: '₹6,00,000',
    aiScore: 99,
    priority: 'Hot',
    tags: ['Enterprise', 'Annual'],
    deadline: 'Closed',
    source: 'Referral',
    aiSuggestion: 'Upsell opportunity: Offer annual plan discount',
    stage: 'Closed',
    phone: '+91 32109 87654',
  },
  {
    id: 'L012',
    name: 'Nisha Kapoor',
    company: 'EduTech Pioneers',
    avatar: 'NK',
    color: '#14B8A6',
    budget: '₹85,000',
    aiScore: 76,
    priority: 'Warm',
    tags: ['EdTech', 'SMB'],
    deadline: 'Closed',
    source: 'Google Ads',
    aiSuggestion: 'Request referral and testimonial — happy customer',
    stage: 'Closed',
    phone: '+91 88776 65544',
  },
];

// ---- AI INSIGHTS ----
export const aiInsights = [
  {
    id: '1',
    type: 'urgent',
    title: '3 leads need follow-up today',
    description: 'Aarav Shah, Sneha Patel, and Ravi Kumar have not been contacted in 48h+',
    action: 'Send Follow-up',
    color: '#EF4444',
  },
  {
    id: '2',
    type: 'opportunity',
    title: 'High intent detected: Arjun Nair',
    description: 'Visited pricing page 4 times today. Optimal time to reach out.',
    action: 'Send Message',
    color: '#2563EB',
  },
  {
    id: '3',
    type: 'automation',
    title: 'Workflow triggered: 12 leads',
    description: 'Automated welcome sequence sent to 12 new WhatsApp leads this morning.',
    action: 'View Details',
    color: '#7C3AED',
  },
  {
    id: '4',
    type: 'win',
    title: 'Deal closed: Dev Sharma ₹6,00,000',
    description: 'Congratulations! InnovateTech Corp signed the Enterprise annual plan.',
    action: 'View Deal',
    color: '#10B981',
  },
];

// ---- RECENT ACTIVITY ----
export const recentActivity = [
  { id: '1', type: 'message', user: 'Aarav Shah', action: 'sent a message', time: '2 min ago', avatar: 'AS', color: '#2563EB' },
  { id: '2', type: 'deal', user: 'Dev Sharma', action: 'deal closed — ₹6,00,000', time: '15 min ago', avatar: 'DS', color: '#8B5CF6' },
  { id: '3', type: 'ai', user: 'AI Bot', action: 'auto-replied to 5 chats', time: '23 min ago', avatar: '🤖', color: '#06B6D4' },
  { id: '4', type: 'lead', user: 'Arjun Nair', action: 'submitted website form', time: '1h ago', avatar: 'AN', color: '#F59E0B' },
  { id: '5', type: 'automation', user: 'Workflow', action: 'follow-up sent to 12 leads', time: '2h ago', avatar: '⚡', color: '#7C3AED' },
  { id: '6', type: 'payment', user: 'Kavya Reddy', action: 'payment reminder sent', time: '3h ago', avatar: 'KR', color: '#EF4444' },
];

// ---- FEATURES ----
export const features = [
  {
    id: '1',
    icon: 'Bot',
    title: 'AI Auto Replies',
    description: 'Let AI handle routine queries 24/7. Trained on your business context for human-like responses.',
    color: '#2563EB',
    gradient: 'from-blue-500 to-blue-600',
    bgColor: '#EFF6FF',
  },
  {
    id: '2',
    icon: 'Inbox',
    title: 'WhatsApp Team Inbox',
    description: 'Unified inbox for your entire team. Assign, collaborate, and close chats faster together.',
    color: '#25D366',
    gradient: 'from-green-500 to-emerald-600',
    bgColor: '#F0FDF4',
  },
  {
    id: '3',
    icon: 'Users',
    title: 'Lead Management',
    description: 'Full CRM with contact profiles, deal stages, notes, and WhatsApp history in one place.',
    color: '#7C3AED',
    gradient: 'from-purple-500 to-violet-600',
    bgColor: '#F5F3FF',
  },
  {
    id: '4',
    icon: 'RefreshCw',
    title: 'Smart Follow-Ups',
    description: 'Never miss a lead again. AI schedules and sends personalized follow-up messages automatically.',
    color: '#06B6D4',
    gradient: 'from-cyan-500 to-sky-600',
    bgColor: '#ECFEFF',
  },
  {
    id: '5',
    icon: 'Star',
    title: 'AI Lead Scoring',
    description: 'Real-time lead scoring powered by AI. Know who to prioritize and when to reach out.',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-orange-500',
    bgColor: '#FFFBEB',
  },
  {
    id: '6',
    icon: 'BarChart3',
    title: 'Customer Analytics',
    description: 'Deep insights into customer behavior, chat patterns, conversion funnels, and revenue trends.',
    color: '#EF4444',
    gradient: 'from-red-500 to-rose-600',
    bgColor: '#FFF1F2',
  },
  {
    id: '7',
    icon: 'Workflow',
    title: 'Workflow Automation',
    description: 'Visual workflow builder for automating lead nurture, onboarding, and re-engagement sequences.',
    color: '#8B5CF6',
    gradient: 'from-violet-500 to-purple-600',
    bgColor: '#F5F3FF',
  },
  {
    id: '8',
    icon: 'Bell',
    title: 'Smart Notifications',
    description: 'Get notified when leads go hot, deals need attention, or payments are overdue.',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-500',
    bgColor: '#FDF2F8',
  },
  {
    id: '9',
    icon: 'MessageSquare',
    title: 'AI Chat Assistant',
    description: 'In-built AI assistant helps your team craft perfect replies in seconds with context awareness.',
    color: '#06B6D4',
    gradient: 'from-cyan-400 to-cyan-600',
    bgColor: '#ECFEFF',
  },
  {
    id: '10',
    icon: 'Globe',
    title: 'Website Form Integration',
    description: 'Capture leads directly from your website and route them to WhatsApp automatically.',
    color: '#10B981',
    gradient: 'from-emerald-400 to-green-600',
    bgColor: '#F0FDF4',
  },
  {
    id: '11',
    icon: 'Shield',
    title: 'WhatsApp API Compliant',
    description: 'Fully compliant with Meta WhatsApp Business API. Official partner with end-to-end encryption.',
    color: '#2563EB',
    gradient: 'from-blue-600 to-indigo-600',
    bgColor: '#EFF6FF',
  },
  {
    id: '12',
    icon: 'Zap',
    title: 'Instant Broadcasts',
    description: 'Send personalized WhatsApp broadcasts to thousands of contacts with AI-powered message optimization.',
    color: '#F59E0B',
    gradient: 'from-yellow-400 to-amber-500',
    bgColor: '#FFFBEB',
  },
];

// ---- TRUSTED BY (fake company names) ----
export const trustedCompanies = [
  { name: 'NovaTech', color: '#2563EB' },
  { name: 'GrowFast', color: '#7C3AED' },
  { name: 'PixelForge', color: '#06B6D4' },
  { name: 'Launchpad', color: '#10B981' },
  { name: 'SwiftScale', color: '#F59E0B' },
  { name: 'DataBridge', color: '#EF4444' },
  { name: 'SkyLoop', color: '#8B5CF6' },
  { name: 'CloudSeed', color: '#EC4899' },
  { name: 'IdeaLab', color: '#2563EB' },
  { name: 'CoreFlow', color: '#06B6D4' },
  { name: 'NextEdge', color: '#7C3AED' },
  { name: 'BrandWave', color: '#10B981' },
  { name: 'OmniDesk', color: '#F59E0B' },
  { name: 'LeapFrog', color: '#EF4444' },
  { name: 'ZenCRM', color: '#8B5CF6' },
  { name: 'SparkFlow', color: '#EC4899' },
];

// ---- AI REPLY SUGGESTIONS ----
export const aiReplySuggestions = [
  "Hi! Thank you for your interest 😊 I'd love to give you a quick walkthrough of our platform. Are you free for a 15-minute demo call this week?",
  "Great question! We offer 3 flexible pricing plans starting at ₹2,999/month. All plans include a 14-day free trial. Shall I send you the full pricing breakdown?",
  "Absolutely! Our AI auto-reply feature is one of our most popular tools. It learns from your conversation history and responds in your brand voice 24/7.",
];

export const quickReplies = [
  '👋 Hi there!',
  '📋 Send Pricing',
  '📅 Schedule Demo',
  '✅ Sounds great!',
  '🙏 Thank you!',
  '⏰ Follow up later',
];
